package morpheus

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

type generatedSnapshot struct {
	paths       []string
	pathsDigest string
	bytesDigest string
}

func snapshotGeneratedFiles(t *testing.T, root string) generatedSnapshot {
	t.Helper()

	contents := make(map[string][]byte)
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("generated path is not a regular file: %s", path)
		}

		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		contents[rel] = data
		return nil
	})
	if err != nil {
		t.Fatalf("walk generated output: %v", err)
	}

	paths := make([]string, 0, len(contents))
	for path := range contents {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	pathsHash := sha256.New()
	bytesHash := sha256.New()
	for _, path := range paths {
		_, _ = pathsHash.Write([]byte(path))
		_, _ = pathsHash.Write([]byte{0})
		_, _ = bytesHash.Write([]byte(path))
		_, _ = bytesHash.Write([]byte{0})
		_, _ = bytesHash.Write(contents[path])
		_, _ = bytesHash.Write([]byte{0})
	}

	return generatedSnapshot{
		paths:       paths,
		pathsDigest: hex.EncodeToString(pathsHash.Sum(nil)),
		bytesDigest: hex.EncodeToString(bytesHash.Sum(nil)),
	}
}

func assertGeneratedSnapshot(t *testing.T, snapshot generatedSnapshot, wantCount int, wantPathsDigest, wantBytesDigest string) {
	t.Helper()
	if len(snapshot.paths) != wantCount {
		t.Errorf("generated file count = %d, want %d; paths:\n%s", len(snapshot.paths), wantCount, strings.Join(snapshot.paths, "\n"))
	}
	if snapshot.pathsDigest != wantPathsDigest {
		t.Errorf("generated path digest = %s, want %s; paths:\n%s", snapshot.pathsDigest, wantPathsDigest, strings.Join(snapshot.paths, "\n"))
	}
	if snapshot.bytesDigest != wantBytesDigest {
		t.Errorf("generated byte digest = %s, want %s", snapshot.bytesDigest, wantBytesDigest)
	}
}

func assertGeneratedKeyPaths(t *testing.T, snapshot generatedSnapshot, want ...string) {
	t.Helper()
	paths := make(map[string]bool, len(snapshot.paths))
	for _, path := range snapshot.paths {
		paths[path] = true
	}
	for _, path := range want {
		if !paths[path] {
			t.Errorf("generated output is missing key path %q", path)
		}
	}
}

func TestGenerateMorpheusFiles_GoWorkerCharacterization(t *testing.T) {
	dir := t.TempDir()
	ctx := testProjectContext()

	written, err := GenerateMorpheusFiles(ctx, dir)
	if err != nil {
		t.Fatalf("GenerateMorpheusFiles failed: %v", err)
	}
	if len(written) != 43 {
		t.Fatalf("GenerateMorpheusFiles wrote %d files, want 43", len(written))
	}

	snapshot := snapshotGeneratedFiles(t, dir)
	assertGeneratedSnapshot(t, snapshot, 43,
		"14f2ad854b5c74b91b0c83eaf2603bc83de8f634bac9eecc7c63f134196debcc",
		"6a21431e62a68a8a17af6b35e7ce4aa1912c9adf300e5d92f8f490009b1ed7e3")
	assertGeneratedKeyPaths(t, snapshot,
		".autonomous/loop.sh",
		".autonomous/config.sh",
		".autonomous/prompts/developer.md",
		".claude/agents/security-reviewer.md",
		".claude/rules/go-service.md",
		"Makefile",
		"go.mod",
		"Dockerfile.worker",
		"external-configs/worker/worker-local.yaml",
		"tasks/TARGET_STATE.md",
	)

	assertGeneratedContent(t, dir, map[string][]string{
		".autonomous/config.sh": {
			"# Go microservice: test-service",
			"# Generated by morp-cli on 2026-03-15",
			"MAX_CYCLES=12",
			"DEVELOPER_MAX_TURNS=28",
			"TESTER_MAX_TURNS=20",
			"REVIEWER_MAX_TURNS=12",
		},
		"go.mod": {
			"module github.com/0merUfuk/test-service",
			"go 1.24.0",
		},
		"Makefile": {
			"WORKER_BINARY := bin/worker",
			"go build -o $(WORKER_BINARY) ./cmd/worker",
		},
		"external-configs/worker/worker-local.yaml": {
			"port: 8091",
			"user: internal",
			"name: internal_main_db",
		},
	})
}

func TestGenerateLoopFiles_Characterization(t *testing.T) {
	dir := t.TempDir()
	ctx := NewLoopContext("characterization-project", "Implement the deterministic characterization goal", CycleConfig{
		MaxCycles:         7,
		DeveloperMaxTurns: 13,
		TesterMaxTurns:    11,
		ReviewerMaxTurns:  5,
	})
	ctx.CreatedDate = "2026-03-15"

	written, err := GenerateLoopFiles(ctx, dir)
	if err != nil {
		t.Fatalf("GenerateLoopFiles failed: %v", err)
	}
	if len(written) != 25 {
		t.Fatalf("GenerateLoopFiles wrote %d files, want 25", len(written))
	}

	snapshot := snapshotGeneratedFiles(t, dir)
	assertGeneratedSnapshot(t, snapshot, 25,
		"94e2591df32ab2cefc3d80acc79c954d9998fd830d3c4a166c8481e59d7855ee",
		"510157903001971c4dc2ffbc88df0f8df851ad5875a00333630d493e733056fb")
	assertGeneratedKeyPaths(t, snapshot,
		".autonomous/loop.sh",
		".autonomous/config.sh",
		".autonomous/prompts/developer.md",
		".autonomous/prompts/security.md",
		".claude/agents/security-reviewer.md",
		".claude/skills/security-scan/SKILL.md",
		"tasks/current-state.md",
		"tasks/TARGET_STATE.md",
		"tasks/DECISIONS.md",
	)

	assertGeneratedContent(t, dir, map[string][]string{
		".autonomous/config.sh": {
			"# Project: characterization-project",
			"# Generated by morp loop on 2026-03-15",
			"MAX_CYCLES=7",
			"DEVELOPER_MAX_TURNS=13",
			"TESTER_MAX_TURNS=11",
			"REVIEWER_MAX_TURNS=5",
		},
		".autonomous/prompts/developer.md": {
			"characterization-project",
		},
		"tasks/TARGET_STATE.md": {
			"Implement the deterministic characterization goal",
		},
		"tasks/current-state.md": {
			"# Current State: CharacterizationProject",
			"freshly scaffolded on 2026-03-15",
		},
	})
}

func assertGeneratedContent(t *testing.T, root string, required map[string][]string) {
	t.Helper()
	for rel, substrings := range required {
		content, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Errorf("read characterized file %q: %v", rel, err)
			continue
		}
		for _, substring := range substrings {
			if !strings.Contains(string(content), substring) {
				t.Errorf("characterized file %q does not contain %q", rel, substring)
			}
		}
	}
}
