package morpheus

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/0merUfuk/the-matrix/internal/cli"
	"github.com/0merUfuk/the-matrix/internal/config"
)

// CORE_FILES are checked for ALL projects (both `morpheus init` and `morpheus loop`).
var CORE_FILES = []string{
	".autonomous/loop.sh",
	".autonomous/config.sh",
	".autonomous/prompts/developer.md",
	".autonomous/prompts/tester.md",
	".autonomous/prompts/reviewer.md",
	"tasks/DECISIONS.md",
	"tasks/TARGET_STATE.md",
	"tasks/todo.md",
}

// INIT_ONLY_FILES are checked only for projects scaffolded via `morpheus init`.
// These files are NOT generated by `morpheus loop`.
var INIT_ONLY_FILES = []string{
	".autonomous/finalizer.sh",
	".autonomous/prompts/finalizer.md",
	".claude/settings.json",
	".claude/SERVICE_CONTEXT.md",
	".claude/NEXT_STEPS.md",
	".claude/DECISIONS.md",
	".claude/KNOWN_ISSUES.md",
	"CLAUDE.md",
}

// EXEC_FILES must have the executable bit set.
var EXEC_FILES = map[string]bool{
	".autonomous/loop.sh":      true,
	".autonomous/finalizer.sh": true,
}

// DoctorMessage represents a single check result from the doctor.
type DoctorMessage struct {
	Status cli.Level // Pass, Fail, or Warn
	Label  string
	Detail string
}

// DoctorResult holds the aggregate results of all doctor checks.
type DoctorResult struct {
	Pass        int
	Fail        int
	Warn        int
	Messages    []DoctorMessage
	NotAService bool // true if the directory is not a morpheus service
}

func (r *DoctorResult) addPass(label, detail string) {
	r.Pass++
	r.Messages = append(r.Messages, DoctorMessage{Status: cli.Pass, Label: label, Detail: detail})
}

func (r *DoctorResult) addFail(label, detail string) {
	r.Fail++
	r.Messages = append(r.Messages, DoctorMessage{Status: cli.Fail, Label: label, Detail: detail})
}

func (r *DoctorResult) addWarn(label, detail string) {
	r.Warn++
	r.Messages = append(r.Messages, DoctorMessage{Status: cli.Warn, Label: label, Detail: detail})
}

// isInitScaffolded checks if the current project was scaffolded via morpheus init
// by looking for finalizer.md. Note: this file is also in INIT_ONLY_FILES — if a
// user deletes it, init-only checks are silently skipped. This is an accepted
// trade-off: finalizer.md is the most reliable discriminator between init and loop projects.
func isInitScaffolded(cwd string) bool {
	return config.FileExists(filepath.Join(cwd, ".autonomous/prompts/finalizer.md"))
}

// CheckDoctor runs all doctor validations against the given directory and
// returns a structured result. It does not print output or call os.Exit,
// making it suitable for testing.
func CheckDoctor(cwd string) DoctorResult {
	var result DoctorResult

	// Guard: check we're in a morpheus service
	if !config.FileExists(filepath.Join(cwd, ".autonomous/loop.sh")) {
		result.NotAService = true
		return result
	}

	// Build the check list: always check core files, add init-only files
	// only if the project was scaffolded via `morpheus init`.
	checkFiles := make([]string, len(CORE_FILES))
	copy(checkFiles, CORE_FILES)
	if isInitScaffolded(cwd) {
		checkFiles = append(checkFiles, INIT_ONLY_FILES...)
	}

	for _, relPath := range checkFiles {
		absPath := filepath.Join(cwd, relPath)
		padded := fmt.Sprintf("%-38s", relPath)

		if !config.FileExists(absPath) {
			result.addFail(padded, "MISSING")
			continue
		}

		// Check executable bit for shell scripts
		if EXEC_FILES[relPath] {
			info, err := os.Stat(absPath)
			if err != nil {
				result.addWarn(padded, "cannot check permissions: "+err.Error())
				continue
			}
			if info.Mode()&0111 == 0 {
				result.addWarn(padded, "not executable — chmod +x")
				continue
			}
		}

		// Special check: settings.json
		if relPath == ".claude/settings.json" {
			content, err := config.ReadFileString(absPath)
			if err != nil {
				result.addWarn(padded, "exists but cannot be read: "+err.Error())
				continue
			}
			var settings map[string]interface{}
			if err := json.Unmarshal([]byte(content), &settings); err != nil {
				result.addFail(padded, "invalid JSON")
				continue
			}
			if _, ok := settings["permissions"]; !ok {
				result.addWarn(padded, "missing 'permissions' key")
				continue
			}
			if perms, ok := settings["permissions"].(map[string]interface{}); ok {
				if _, ok := perms["allow"].([]interface{}); !ok {
					result.addFail(padded, "missing permissions.allow array")
					continue
				}
			}
		}

		// Special check: tasks/todo.md skeleton detection
		if relPath == "tasks/todo.md" {
			content, err := config.ReadFileString(absPath)
			if err != nil {
				result.addWarn(padded, "exists but cannot be read: "+err.Error())
				continue
			}
			if strings.Contains(content, "skeleton template") {
				result.addWarn(padded, "skeleton template (Claude was unavailable)")
				continue
			}
		}

		result.addPass(padded, "OK")
	}

	// Tech detection
	hasGoRules := config.FileExists(filepath.Join(cwd, ".claude/rules/go-service.md"))
	hasNodeRules := config.FileExists(filepath.Join(cwd, ".claude/rules/node-service.md"))
	if !hasGoRules && !hasNodeRules {
		result.addWarn(fmt.Sprintf("%-38s", "tech detection"), "neither go-service.md nor node-service.md found")
	}

	return result
}

// RunDoctor validates a scaffolded service before running the loop.
// It prints styled output and calls os.Exit(1) on critical failures.
func RunDoctor(projectDir string) {
	result := CheckDoctor(projectDir)
	theme := cli.GetTheme()

	if result.NotAService {
		fmt.Fprintln(os.Stderr, theme.ErrorBox("Not a morpheus service",
			"Run morpheus doctor from a scaffolded service directory."))
		os.Exit(1)
	}

	serviceName := filepath.Base(projectDir)
	fmt.Print(theme.Banner("morpheus doctor", serviceName))
	fmt.Println()

	for _, msg := range result.Messages {
		fmt.Println(theme.StatusLine(msg.Status, msg.Label, msg.Detail))
	}

	// Summary
	fmt.Println()
	if result.Fail > 0 {
		label := "warning"
		if result.Warn > 1 {
			label = "warnings"
		}
		critLabel := "critical"
		if result.Fail > 1 {
			critLabel = "criticals"
		}
		parts := []string{theme.Error.Render(fmt.Sprintf("%d %s", result.Fail, critLabel))}
		if result.Warn > 0 {
			parts = append(parts, theme.Warning.Render(fmt.Sprintf("%d %s", result.Warn, label)))
		}
		fmt.Println(theme.ErrorBox("Fix before running .autonomous/loop.sh",
			strings.Join(parts, ", ")))
		os.Exit(1)
	} else if result.Warn > 0 {
		label := "warning"
		if result.Warn > 1 {
			label = "warnings"
		}
		fmt.Println(theme.WarnBox(
			fmt.Sprintf("%d %s — consider fixing before running .autonomous/loop.sh", result.Warn, label)))
	} else {
		fmt.Println(theme.SuccessBox("All checks passed — ready to run .autonomous/loop.sh"))
	}
	fmt.Println()
}
