package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/0merUfuk/the-matrix/internal/config"
)

func init() {
	Register(&agentsMDFormat{})
}

type agentsMDFormat struct{}

func (f *agentsMDFormat) Name() string        { return "agents-md" }
func (f *agentsMDFormat) Description() string { return "AGENTS.md — single consolidated file" }

func (f *agentsMDFormat) Export(docs []KnowledgeDoc, targetDir string, opts ExportOpts) error {
	if err := config.EnsureDir(targetDir); err != nil {
		return fmt.Errorf("creating target directory: %w", err)
	}

	var b strings.Builder

	// Header with auto-generated notice
	fmt.Fprintf(&b, "# AGENTS.md — %s\n\n", opts.StackName)
	b.WriteString("> Auto-generated by `oracle export`. Do not edit manually — re-run export to refresh.\n\n")

	// Table of contents
	b.WriteString("## Table of Contents\n\n")
	for _, doc := range docs {
		anchor := strings.ReplaceAll(strings.ToLower(doc.Title), " ", "-")
		// Strip characters that aren't valid in markdown anchors
		anchor = sanitizeAnchor(anchor)
		fmt.Fprintf(&b, "- [%s](#%s)\n", doc.Title, anchor)
	}
	b.WriteString("\n---\n\n")

	// Full content for all topics
	for i, doc := range docs {
		stripped := StripFrontmatter(doc.Content)

		// Replace the original # heading with ## heading for consolidation
		stripped = promoteToSection(doc.Title, stripped)

		b.WriteString(stripped)

		// Add separator between topics
		if i < len(docs)-1 {
			b.WriteString("\n\n---\n\n")
		} else {
			b.WriteString("\n")
		}
	}

	outPath := filepath.Join(targetDir, "AGENTS.md")
	return os.WriteFile(outPath, []byte(b.String()), 0644)
}

// promoteToSection replaces the first # heading with ## or prepends ## if no heading found.
func promoteToSection(title, content string) string {
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "# ") && !strings.HasPrefix(trimmed, "## ") {
			lines[i] = "## " + title
			return strings.Join(lines, "\n")
		}
	}
	// No # heading found — prepend one
	return "## " + title + "\n\n" + content
}

// sanitizeAnchor removes characters that aren't valid in GitHub markdown anchors.
func sanitizeAnchor(s string) string {
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' {
			b.WriteRune(c)
		}
	}
	return b.String()
}
