package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/0merUfuk/the-matrix/internal/config"
)

func init() {
	Register(&copilotFormat{})
}

type copilotFormat struct{}

func (f *copilotFormat) Name() string { return "copilot" }
func (f *copilotFormat) Description() string {
	return ".github/copilot-instructions.md — consolidated"
}

func (f *copilotFormat) Export(docs []KnowledgeDoc, targetDir string, opts ExportOpts) error {
	githubDir := filepath.Join(targetDir, ".github")
	if err := config.EnsureDir(githubDir); err != nil {
		return fmt.Errorf("creating .github/: %w", err)
	}

	var b strings.Builder

	// Header
	b.WriteString("# Copilot Instructions\n\n")
	fmt.Fprintf(&b, "> Auto-generated by `oracle export` from %s knowledge docs. Do not edit manually.\n\n", opts.StackName)

	// Full content for all topics
	for i, doc := range docs {
		stripped := StripFrontmatter(doc.Content)
		stripped = promoteToSection(doc.Title, stripped)

		b.WriteString(stripped)

		if i < len(docs)-1 {
			b.WriteString("\n\n---\n\n")
		} else {
			b.WriteString("\n")
		}
	}

	outPath := filepath.Join(githubDir, "copilot-instructions.md")
	return os.WriteFile(outPath, []byte(b.String()), 0644)
}
