package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/0merUfuk/the-matrix/internal/config"
)

func init() {
	Register(&windsurfFormat{})
}

type windsurfFormat struct{}

func (f *windsurfFormat) Name() string        { return "windsurf" }
func (f *windsurfFormat) Description() string { return ".windsurfrules — single flat file" }

func (f *windsurfFormat) Export(docs []KnowledgeDoc, targetDir string, opts ExportOpts) error {
	if err := config.EnsureDir(targetDir); err != nil {
		return fmt.Errorf("creating target directory: %w", err)
	}

	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "# Windsurf Rules — %s\n\n", opts.StackName)
	b.WriteString("> Auto-generated by `oracle export`. Do not edit manually — re-run export to refresh.\n\n")

	// Full content for all topics
	for i, doc := range docs {
		stripped := StripFrontmatter(doc.Content)
		stripped = promoteToSection(doc.Title, stripped)

		b.WriteString(stripped)

		if i < len(docs)-1 {
			b.WriteString("\n\n---\n\n")
		} else {
			b.WriteString("\n")
		}
	}

	outPath := filepath.Join(targetDir, ".windsurfrules")
	return os.WriteFile(outPath, []byte(b.String()), 0644)
}
