package oracle

import (
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/0merUfuk/the-matrix/internal/cli"
)

// DocInfo holds metadata about a validated doc for index generation.
type DocInfo struct {
	Filename string
	Content  string
}

var createdDateRe = regexp.MustCompile(`\*\*Created\*\*:\s*(\d{4}-\d{2}-\d{2})`)

// BuildIndex generates the _index.md content for a set of injected docs.
func BuildIndex(docs []DocInfo, fromDir, toDir string) string {
	today := time.Now().Format("2006-01-02")
	relFrom := cli.PathToHome(fromDir)
	relTo := cli.PathToHome(toDir)

	var rows []string
	for _, doc := range docs {
		lineCount := len(strings.Split(doc.Content, "\n"))
		created := "unknown"
		if m := createdDateRe.FindStringSubmatch(doc.Content); m != nil {
			created = m[1]
		}
		rows = append(rows, fmt.Sprintf("| `%s` | %s | %d | %s |", doc.Filename, created, lineCount, today))
	}

	lines := []string{
		"**Version**: 1.0",
		fmt.Sprintf("**Created**: %s", today),
		fmt.Sprintf("**Last Updated**: %s", today),
		"**Authors:** Oracle CLI (injected)",
		"",
		"---",
		"",
		"# Knowledge Index",
		"",
		"> Auto-generated by `oracle inject`. Do not edit manually — re-run inject to refresh.",
		"",
		fmt.Sprintf("**Source**: `%s`", relFrom),
		fmt.Sprintf("**Target**: `%s`", relTo),
		fmt.Sprintf("**Injected**: %s", today),
		fmt.Sprintf("**Docs**: %d", len(docs)),
		"",
		"---",
		"",
		"## Files",
		"",
		"| File | Created | Lines | Injected |",
		"|------|---------|-------|----------|",
	}
	lines = append(lines, rows...)
	lines = append(lines, "")

	return strings.Join(lines, "\n")
}
